### ISSUE TITLE
I don't know what is going on?

### ISSUE THREAD

**Issue by Daymond2253** [Dplayend/OdysseyHUD#11]
![2022-06-18_13 53 28](https://user-images.githubusercontent.com/96675624/174429489-a3c21148-9441-4e28-b476-afc44495508e.png)

I am not able to see the animation and black border that you show in your sample image.

**Comment by Dplayend** [comment]
do you have other mods they alter the hud?, write your modpack

**Comment by Daymond2253** [comment]
![image](https://user-images.githubusercontent.com/96675624/174453234-f1e889b2-8186-47aa-bee6-610da75e4f84.png)

**Comment by Daymond2253** [comment]
GOT IT with offerHUD  it's not working well. By any chance, do you have a fix for that.

**Comment by Dplayend** [comment]
oh, thanks, i will do a compat for that

**Comment by Daymond2253** [comment]
> oh, thanks, i will do a compat for that

Ok, thanks!
