### ISSUE TITLE
Cause stuck when reload resourcepack in game 1.18.2 fabric

### ISSUE THREAD

**Issue by SettingDust** [Dplayend/OdysseyHUD#12]
`MixinItemStack#getTooltip`
`this.mc` is null

**Comment by Dplayend** [comment]
i dont see the problem, do you use another resourcepack?
https://i.imgur.com/I6jMtbb.mp4

**Comment by SettingDust** [comment]
Yes. The error is the `this.mc` is null

**Comment by Dplayend** [comment]
what is the resource pack?

**Comment by SettingDust** [comment]
Same disable all resource packs 
https://pastes.dev/Kpm7yhriNF

**Comment by Fourbo** [comment]
I have the same issue when using odysseyhud-fabric-1.19-v4.6.jar on Fabric 0.14.8. It doesn't give a crash when enabling resource packs in the main menu, but it crashes if I try to do it in a singleplayer world.

**Comment by Dplayend** [comment]
fix it in the 1.19.x v5.1
