### ISSUE TITLE
[Forge 1.18] HUD is only displayed if clock is in inventory, even when the config is changed

### ISSUE THREAD

**Issue by GeorgeOrwell1** [Dplayend/OdysseyHUD#7]
Even if I've changed the `mustHaveClockInInventory` to `false` I still need to have the clock in my inventory to see the HUD.

Log:
[latest.log](https://github.com/Dplayend/OdysseyHUD/files/7698795/latest.log)

**Comment by Dplayend** [comment]
fixed, thanks for the report
