### ISSUE TITLE
[Forge 1.18.2] Crash when joining world

### ISSUE THREAD

**Issue by ffuentesm** [Dplayend/OdysseyHUD#9]
The game is crashing when I join the world, I suspect is due to this version still being of the 1.18.1 and not 1.18.2
![image](https://user-images.githubusercontent.com/44974827/165417727-1a6e1cbd-9f8e-4fb2-bec8-68697e8d19db.png)

![image](https://user-images.githubusercontent.com/44974827/165417648-433ca185-7684-4040-884a-7ecf21a8745a.png)
odysseyhud-forge-1.18-2.0.jar

https://crashy.net/VkElxxgBjtrgjm0IiuJ9
https://bytebin.lucko.me/Bpkxj0Hjtd

**Comment by Dplayend** [comment]
the mod is for 1.18 not 1.18.2, now i  made the new version for the 1.18.2, thats why not work
